---
# role: samba_dc
# file: tasks/directory.yml

- name: SAMBA_DC | Reserve DNS names against client registration
  jomrr.samba.samba_dns_record:
    server: "{{ samba_dc_hostname }}.{{ samba_dc_realm | lower }}"
    realm: "{{ samba_dc_realm | upper }}"
    bind_username: Administrator
    bind_password: "{{ samba_dc_admin_password }}"
    zone: "{{ samba_dc_realm | lower }}"
    name: "{{ __samba_dc_reserved_name }}"
    type: A
    value: 127.0.0.1
    state: present
  loop: "{{ samba_dc_dns_reserved_names }}"
  loop_control:
    loop_var: __samba_dc_reserved_name

- name: SAMBA_DC | Configure the domain password policy
  samba_dc_password_policy:
    server: "{{ samba_dc_hostname }}.{{ samba_dc_realm | lower }}"
    realm: "{{ samba_dc_realm | upper }}"
    bind_username: Administrator
    bind_password: "{{ samba_dc_admin_password }}"
    settings: "{{ samba_dc_password_policy }}"

- name: SAMBA_DC | Configure fine-grained password policies
  samba_dc_password_settings:
    server: "{{ samba_dc_hostname }}.{{ samba_dc_realm | lower }}"
    realm: "{{ samba_dc_realm | upper }}"
    bind_username: Administrator
    bind_password: "{{ samba_dc_admin_password }}"
    name: "{{ __samba_dc_password_settings.name }}"
    precedence: "{{ __samba_dc_password_settings.precedence | default(omit) }}"
    applies_to: "{{ __samba_dc_password_settings.applies_to | default([]) }}"
    settings: "{{ samba_dc_password_policy | combine(__samba_dc_password_settings.settings | default({})) }}"
    state: "{{ __samba_dc_password_settings.state | default('present') }}"
  loop: "{{ samba_dc_password_settings }}"
  loop_control:
    loop_var: __samba_dc_password_settings
    label: "{{ __samba_dc_password_settings.name }}"
