---
# role: samba_ad_dc
# file: tasks/main.yml

- name: SAMBA_AD_DC | Install domain controller packages
  ansible.builtin.import_tasks: install.yml

- name: SAMBA_AD_DC | Initialize the domain controller
  ansible.builtin.import_tasks: initialize.yml

- name: SAMBA_AD_DC | Prepare the Windows LAPS schema
  become: true
  become_user: root
  jomrr.samba.samba_schema_extension:
    extension: laps
  when: samba_ad_dc_laps | bool
  notify: restart domain controller

- name: SAMBA_AD_DC | Apply pending configuration changes
  ansible.builtin.meta: flush_handlers

- name: SAMBA_AD_DC | Enable and start the domain controller
  become: true
  become_user: root
  ansible.builtin.systemd_service:
    name: "{{ __samba_ad_dc_service }}"
    masked: false
    enabled: true
    state: started

- name: SAMBA_AD_DC | Configure domain password policies
  ansible.builtin.import_tasks: passwords.yml
  module_defaults:
    group/jomrr.samba.all:
      server: "{{ samba_ad_dc_hostname }}.{{ samba_ad_dc_realm | lower }}"
      realm: "{{ samba_ad_dc_realm | upper }}"
      bind_username: Administrator
      bind_password: "{{ samba_ad_dc_admin_password }}"
