---
# role: samba_ad_dc
# file: tasks/passwords.yml

- name: SAMBA_AD_DC | Configure the domain password policy
  jomrr.samba.samba_password_policy:
    settings: "{{ samba_ad_dc_password_policy }}"
  when: samba_ad_dc_password_policy | length > 0

- name: SAMBA_AD_DC | Configure fine-grained password policies
  jomrr.samba.samba_password_settings:
    name: "{{ __samba_ad_dc_password_settings.name }}"
    precedence: "{{ __samba_ad_dc_password_settings.precedence | default(omit) }}"
    applies_to: "{{ __samba_ad_dc_password_settings.applies_to | default([]) }}"
    settings: "{{ samba_ad_dc_password_policy | combine(__samba_ad_dc_password_settings.settings | default({})) }}"
    state: "{{ __samba_ad_dc_password_settings.state | default('present') }}"
  loop: "{{ samba_ad_dc_password_settings }}"
  loop_control:
    loop_var: __samba_ad_dc_password_settings
    label: "{{ __samba_ad_dc_password_settings.name }}"
