---
# role: samba_dc
# file: tasks/provision.yml

- name: SAMBA_DC | Install the validated domain controller configuration
  ansible.builtin.template:
    src: smb.conf.j2
    dest: "{{ __samba_dc_config }}"
    owner: root
    group: root
    mode: "0644"
    backup: true
    validate: "{{ __samba_dc_validate }}"
  notify: restart domain controller

- name: SAMBA_DC | Provision the first controller of the new domain
  jomrr.samba.samba_provision:
    realm: "{{ samba_dc_realm | upper }}"
    domain: "{{ samba_dc_domain | upper }}"
    hostname: "{{ samba_dc_hostname }}"
    admin_password: "{{ samba_dc_admin_password }}"
    dns_backend: SAMBA_INTERNAL
    function_level: "{{ samba_dc_function_level }}"
    use_rfc2307: "{{ samba_dc_use_rfc2307 }}"
    state: present
  no_log: true

- name: SAMBA_DC | Install the provisioned Kerberos configuration
  ansible.builtin.copy:
    src: "{{ __samba_dc_private_dir }}/krb5.conf"
    dest: /etc/krb5.conf
    remote_src: true
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: restart domain controller
