---
# role: samba_dc
# file: molecule/dev/molecule.yml

dependency:
  name: "galaxy"
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
    role-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.builtin.default"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
    prepare: "../resources/playbooks/prepare.yml"
    side_effect: "../resources/playbooks/side_effect.yml"
  inventory:
    group_vars:
      all:
        __samba_dc_test_rootless: true
        samba_dc_realm: "AD.EXAMPLE.TEST"
        samba_dc_domain: "EXAMPLE"
        samba_dc_hostname: "dc1"
        samba_dc_admin_password: "Molecule-Only-Adm1n!"
        samba_dc_tls_keyfile: "/etc/samba/tls/dc1.key"
        samba_dc_tls_certfile: "/etc/samba/tls/dc1.crt"
        samba_dc_tls_cafile: "/etc/samba/tls/ca.crt"
        __samba_dc_test_cafile: "/etc/samba/tls/ca.crt"
    host_vars:
      samba-dc-debian:
        samba_dc_tls_keyfile: "tls/key.pem"
        samba_dc_tls_certfile: "tls/cert.pem"
        samba_dc_tls_cafile: "tls/ca.pem"
        __samba_dc_test_cafile: "/var/lib/samba/private/tls/ca.pem"
      samba-dc-ubuntu:
        samba_dc_tls_keyfile: "tls/key.pem"
        samba_dc_tls_certfile: "tls/cert.pem"
        samba_dc_tls_cafile: "tls/ca.pem"
        __samba_dc_test_cafile: "/var/lib/samba/private/tls/ca.pem"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "dependency"
    - "destroy"
    - "syntax"
    - "create"
    - "prepare"
    - "converge"
    - "idempotence"
    - "check"
    - "verify"
    - "side_effect"
    - "converge"
    - "idempotence"
    - "verify"
    - "destroy"
  name: "dev"
platforms:
  - name: "samba-dc-almalinux"
    hostname: "dc1"
    image: "docker.io/jomrr/molecule-almalinux:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    extra_opts:
      - "--tmpfs=/var/lib/samba:rw,size=1g,mode=0755"
  - name: "samba-dc-debian"
    hostname: "dc1"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    extra_opts:
      - "--tmpfs=/var/lib/samba:rw,size=1g,mode=0755"
  - name: "samba-dc-fedora"
    hostname: "dc1"
    image: "docker.io/jomrr/molecule-fedora:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    extra_opts:
      - "--tmpfs=/var/lib/samba:rw,size=1g,mode=0755"
  - name: "samba-dc-suse"
    hostname: "dc1"
    image: "docker.io/jomrr/molecule-opensuse-tumbleweed:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    extra_opts:
      - "--tmpfs=/var/lib/samba:rw,size=1g,mode=0755"
  - name: "samba-dc-ubuntu"
    hostname: "dc1"
    image: "docker.io/jomrr/molecule-ubuntu:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    extra_opts:
      - "--tmpfs=/var/lib/samba:rw,size=1g,mode=0755"
