---
# role: samba_dc
# file: molecule/resources/playbooks/converge.yml

- name: SAMBA_DC | Converge the first domain controller
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') }}"
